apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: users
    module: policy
    project: ship-krew
  name: users-policy-rego
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 50Mi
  hostPath:
    path: /home/pi/Desktop/ship-krew/users/policy/rego
    # TODO: Retain may not be the best here.
  persistentVolumeReclaimPolicy: Retain
  # TODO: this must be changed
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-policy-rego
  namespace: ship-krew-backend
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      app: users
      module: policy
      project: ship-krew
  # TODO: this must be changed
  storageClassName: local-path