### ServiceProfile for users-api.ship-krew-backend ###
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: users-policy.ship-krew-backend.svc.cluster.local
  namespace: ship-krew-backend
spec:
  routes:
  - name: Get permissions
    condition:
      pathRegex: '/settings/permissions'
      method: POST
    responseClasses:
    - condition:
        status:
          min: 400
          max: 599
      isFailure: true
    isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 5
    ttl: 10s