apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: users
    module: login
    project: ship-krew
  name: users-login-views
spec:
  accessModes:
  # TODO: for changing html on admin this may not be ideal
  - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/pi/Desktop/ship-krew/views
    # TODO: Retain may not be the best here.
  persistentVolumeReclaimPolicy: Retain
  # TODO: this must be changed
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-login-views
  namespace: ship-krew-backend
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: users
      module: login
      project: ship-krew
  # TODO: this must be changed
  storageClassName: local-path