apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
    module: api
    project: ship-krew
  name: users-api
  namespace: ship-krew-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: users
    module: api
    project: ship-krew
  sessionAffinity: None
  type: ClusterIP